//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf StronglyTypedResourceBuilder tarafından otomatik olarak oluşturuldu
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // /str seçeneği ile veya Visual Studio projesini yeniden kur.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının CurrentUICulture 
        ///   özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a Customer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AddACustomer {
            get {
                return ResourceManager.GetString("AddACustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Car benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AddNewCar {
            get {
                return ResourceManager.GetString("AddNewCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Process benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AddProcess {
            get {
                return ResourceManager.GetString("AddProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Age benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Call benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Call Records benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CallRecords {
            get {
                return ResourceManager.GetString("CallRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Car benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Car Branch benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CarBranch {
            get {
                return ResourceManager.GetString("CarBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Car List benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CarList {
            get {
                return ResourceManager.GetString("CarList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Car Maintanance Time benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CarMaintananceTime {
            get {
                return ResourceManager.GetString("CarMaintananceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Language benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change LOGO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ChangeLOGO {
            get {
                return ResourceManager.GetString("ChangeLOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Your Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Licence Plate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ChooseLicencePlate {
            get {
                return ResourceManager.GetString("ChooseLicencePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Product benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ChooseProduct {
            get {
                return ResourceManager.GetString("ChooseProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Type benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ChooseType {
            get {
                return ResourceManager.GetString("ChooseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact To Customer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ContactToCustomer {
            get {
                return ResourceManager.GetString("ContactToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CustomerList benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CustomerList {
            get {
                return ResourceManager.GetString("CustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CustomerName benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Edit Or Process To Car benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DeleteEditOrProcessToCar {
            get {
                return ResourceManager.GetString("DeleteEditOrProcessToCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Details benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Customer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit This Car benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EditThisCar {
            get {
                return ResourceManager.GetString("EditThisCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Licence benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Licence Plate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LicencePlate {
            get {
                return ResourceManager.GetString("LicencePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Never Call Again benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NeverCall {
            get {
                return ResourceManager.GetString("NeverCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number Of People To Call benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NumberOfPeopleToCall {
            get {
                return ResourceManager.GetString("NumberOfPeopleToCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OilDate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OilDate {
            get {
                return ResourceManager.GetString("OilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Records benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProcessRecords {
            get {
                return ResourceManager.GetString("ProcessRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sales benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Repassword Code benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SendRepasswordCode {
            get {
                return ResourceManager.GetString("SendRepasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Processes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ShowProcesses {
            get {
                return ResourceManager.GetString("ShowProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stats benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stores benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subject benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surname benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telephone benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turkish benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Users benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write Your Message Here To benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WriteYourMessageHere {
            get {
                return ResourceManager.GetString("WriteYourMessageHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You Have To Call benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string YouHaveToCall {
            get {
                return ResourceManager.GetString("YouHaveToCall", resourceCulture);
            }
        }
    }
}
