//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilContRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallRecord
    {
        public int ID { get; set; }
        public int ProcessID { get; set; }
        public System.DateTime Time { get; set; }
        public string CustomerName { get; set; }
        public string Car { get; set; }
        public string LicencePlate { get; set; }
        public string Telephone { get; set; }
    }
}
