//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilContRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarInfo()
        {
            this.ProcessINFO = new HashSet<ProcessINFO>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string LicencePlate { get; set; }
        public string CarBranch { get; set; }
        public string Model { get; set; }
        public Nullable<int> Age { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> OilDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessINFO> ProcessINFO { get; set; }
    }
}
