//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilContRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDatas
    {
        public decimal TotalRev { get; set; }
        public int Sales { get; set; }
        public int StoreNumber { get; set; }
        public int Customers { get; set; }
    }
}
