//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilContRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fuelrmEntities : DbContext
    {
        public fuelrmEntities()
            : base("name=fuelrmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<CarInfo> CarInfo { get; set; }
        public virtual DbSet<Password_LOG> Password_LOG { get; set; }
        public virtual DbSet<ProcessContent> ProcessContent { get; set; }
        public virtual DbSet<ProcessINFO> ProcessINFO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<CompanyDatas> CompanyDatas { get; set; }
        public virtual DbSet<URUNLISTEM> URUNLISTEM { get; set; }
    }
}
