//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilContRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessINFO
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ContentID { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<bool> IsCalled { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual CarInfo CarInfo { get; set; }
        public virtual ProcessContent ProcessContent { get; set; }
    }
}
